#2 Fix bug with printing.
DEVICE is a torch.device. We treated it as a string. This patch fixes that type issue.

We were getting this problem:
          Exception Class: <class 'TypeError'>
          Exception Args: ("descriptor 'upper' requires a 'str' object but received a 'torch.device'",)
          Traceback (most recent call last):
            File "/home/pnguyen/code/impact_of_attention/misc_utilities.py", line 55, in func_wrapped
              func(*args, **kwargs)
            File "./main.py", line 169, in main
              elif args.deploy_comparison_documents:
            File "./main.py", line 139, in train_models
              return
            File "/home/pnguyen/code/impact_of_attention/models.py", line 458, in train
              print(f'Starting training on the {str.upper(DEVICE)}')
          TypeError: descriptor 'upper' requires a 'str' object but received a 'torch.device'
          > /home/pnguyen/code/impact_of_attention/models.py(458)train()
          -> print(f'Starting training on the {str.upper(DEVICE)}')
          (Pdb)